-- W10-08: Seed 10 verified beauty industry RSS sources
--
-- VERIFICATION LOG (2026-03-06, Session 29):
--   Each URL was curl-verified (HTTP 200 + <?xml RSS/Atom content) against
--   Socelle-Intelligence-Bot/1.0 User-Agent before inclusion.
--   403/401 candidates were replaced; 10 final sources confirmed.
--
-- Approval: SOCELLE_DATA_PROVENANCE_POLICY.md §1 Tier 2 — Public RSS feeds (allowed).
-- Content rule: headline + excerpt + link only. Full-text must NOT be displayed.
-- ADD ONLY — never modify this file after applying to production.
-- To add/update sources: insert directly or apply a new numbered seed migration.

insert into public.rss_sources (name, feed_url, category, verticals, refresh_minutes)
values
  -- ── Trade / Professional Beauty ────────────────────────────────────────────
  (
    'WWD Beauty',
    'https://wwd.com/beauty-industry-news/feed/',
    'professional_beauty',
    array['skincare_brands', 'beauty_tech'],
    60
  ),
  (
    'Beauty Independent',
    'https://www.beautyindependent.com/feed/',
    'professional_beauty',
    array['skincare_brands', 'wellness'],
    60
  ),
  (
    'Happi Magazine',
    'https://www.happi.com/feed/',         -- verified 200 + RSS XML 2026-03-06
    'trade_industry',
    array['skincare_brands', 'beauty_tech'],
    120
  ),
  (
    'Modern Salon',
    'https://www.modernsalon.com/rss',     -- verified 200 + RSS XML 2026-03-06
    'professional_beauty',
    array['salon', 'hair_salon'],
    60
  ),
  (
    'Salon Today',
    'https://www.salontoday.com/rss',      -- verified 200 + RSS XML 2026-03-06
    'professional_beauty',
    array['salon', 'hair_salon'],
    60
  ),
  -- ── Spa / Wellness ─────────────────────────────────────────────────────────
  (
    'Organic Spa Magazine',
    'https://organicspamagazine.com/feed', -- verified 200 + RSS XML 2026-03-06
    'wellness',
    array['spa', 'wellness'],
    120
  ),
  -- ── Consumer Beauty (trend signal, ingredient sentiment) ───────────────────
  (
    'Allure',
    'https://www.allure.com/feed/rss',
    'skincare_brands',
    array['skincare_brands', 'makeup', 'hair_salon'],
    60
  ),
  (
    'New Beauty',
    'https://www.newbeauty.com/feed/',     -- verified 200 + RSS XML 2026-03-06
    'skincare_brands',
    array['skincare_brands', 'wellness'],
    60
  ),
  (
    'Elle Beauty',
    'https://www.elle.com/rss/beauty.xml', -- verified 200 2026-03-06
    'skincare_brands',
    array['skincare_brands', 'makeup'],
    60
  ),
  (
    'Harper''s Bazaar Beauty',
    'https://www.harpersbazaar.com/rss/beauty.xml', -- verified 200 2026-03-06
    'skincare_brands',
    array['skincare_brands', 'makeup'],
    60
  )
on conflict (feed_url) do nothing;

-- ── Sources that failed verification (403/401) — NOT SEEDED ──────────────────
-- The following were originally planned but returned non-200 responses on
-- 2026-03-06 and could not be confirmed as publicly accessible feeds:
--   GCI Magazine (gcimagazine.com)        — 403, no confirmed feed path
--   American Spa (americanspa.com)        — 403, no confirmed feed path
--   Skin Inc Magazine (skininc.com)       — 403, no confirmed feed path
--   Aesthetic Authority                   — 401, requires authentication
--   MedEsthetics (medestheticsmag.com)    — 403, no confirmed feed path
-- Action: re-verify quarterly. If a valid feed path is confirmed, add via
-- a new seed migration (do NOT edit this file once applied to production).
