import { useState } from 'react';
import {
  X,
  FileText,
  ChevronDown,
  ChevronUp,
  Bot,
  CreditCard,
  CheckSquare,
  Square,
} from 'lucide-react';

interface BriefGeneratorProps {
  onClose: () => void;
}

const DEMO_SIGNALS = [
  { id: 's1', title: 'Peptide Facial Demand Surge', selected: false },
  { id: 's2', title: 'LED Light Therapy Adoption', selected: false },
  { id: 's3', title: 'Retinol Alternative Interest', selected: false },
  { id: 's4', title: 'Scalp Treatment Market Growth', selected: false },
  { id: 's5', title: 'Clean Beauty Certification Demand', selected: false },
];

const OUTPUT_FORMATS = ['PDF', 'Email', 'Slide'] as const;
const AUDIENCES = ['Team', 'Client', 'Executive'] as const;

const DEMO_BRIEF = `Intelligence Brief: Emerging Treatment Trends — Q1 2026

The professional beauty and medspa sector is experiencing a notable shift toward peptide-based and LED-enhanced treatment modalities. Our signal analysis across 37+ data sources indicates that peptide facial demand has increased 34% quarter-over-quarter, making it the fastest-growing treatment category in the clinical esthetics space. This growth is corroborated by a 28% increase in professional training module completions for peptide protocols on the SOCELLE platform, suggesting that practitioners are actively upskilling to meet anticipated demand.

Concurrently, LED light therapy device adoption among spas and medspas has risen 22% in the past quarter. Red light therapy leads this category, with increasing evidence supporting its efficacy for anti-aging and post-procedure recovery. The convergence of consumer awareness (driven by social media education content) and professional adoption creates a window of opportunity for operators who can add these services within the next 30-60 days.

For operators and clinic owners, the recommended action is to evaluate current menu offerings against these demand signals. Businesses that added trending treatments within 45 days of a signal peak historically captured 2.3x the revenue uplift compared to late adopters. We recommend prioritizing peptide facials for immediate menu addition and exploring LED therapy device partnerships for Q2 deployment.`;

export function BriefGenerator({ onClose }: BriefGeneratorProps) {
  const [signals, setSignals] = useState(DEMO_SIGNALS);
  const [outputFormat, setOutputFormat] = useState<(typeof OUTPUT_FORMATS)[number]>('PDF');
  const [audience, setAudience] = useState<(typeof AUDIENCES)[number]>('Team');
  const [generated, setGenerated] = useState(false);
  const [showEvidence, setShowEvidence] = useState(false);

  const selectedCount = signals.filter((s) => s.selected).length;

  const toggleSignal = (id: string) => {
    setSignals((prev) =>
      prev.map((s) => (s.id === id ? { ...s, selected: !s.selected } : s))
    );
  };

  const handleGenerate = () => {
    if (selectedCount > 0) {
      setGenerated(true);
    }
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/40 z-50"
        onClick={onClose}
        role="presentation"
      />

      {/* Modal */}
      <div className="fixed inset-x-4 top-[5%] bottom-[5%] md:inset-x-auto md:left-1/2 md:-translate-x-1/2 md:w-full md:max-w-2xl z-50 flex flex-col bg-white rounded-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#6E879B]/10">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-[#E8EDF1] flex items-center justify-center">
              <FileText className="w-4 h-4 text-[#6E879B]" />
            </div>
            <div>
              <h2 className="font-sans text-base font-semibold text-[#141418]">
                Brief Generator
              </h2>
              <p className="text-xs font-sans text-gray-400">
                Create intelligence briefs from signals
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-[10px] font-semibold bg-[#A97A4C]/10 text-[#A97A4C] px-2 py-0.5 rounded-full">
              DEMO
            </span>
            <button
              type="button"
              onClick={onClose}
              className="w-8 h-8 rounded-lg hover:bg-[#F6F3EF] flex items-center justify-center transition-colors"
            >
              <X className="w-4 h-4 text-gray-400" />
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-6">
          {/* AI badge */}
          <div className="flex items-center gap-2 text-xs font-sans text-gray-400">
            <Bot className="w-3.5 h-3.5" />
            <span>Generated by AI</span>
            <span className="mx-1">|</span>
            <CreditCard className="w-3.5 h-3.5" />
            <span>25 credits</span>
          </div>

          {!generated ? (
            <>
              {/* Signal selection */}
              <div>
                <label className="text-xs font-sans font-semibold text-gray-400 uppercase tracking-wider block mb-3">
                  Select Signals ({selectedCount} selected)
                </label>
                <div className="space-y-2">
                  {signals.map((signal) => (
                    <button
                      key={signal.id}
                      type="button"
                      onClick={() => toggleSignal(signal.id)}
                      className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl border transition-colors text-left ${
                        signal.selected
                          ? 'border-[#6E879B] bg-[#E8EDF1]'
                          : 'border-[#6E879B]/10 hover:bg-[#F6F3EF]'
                      }`}
                    >
                      {signal.selected ? (
                        <CheckSquare className="w-4 h-4 text-[#6E879B] flex-shrink-0" />
                      ) : (
                        <Square className="w-4 h-4 text-gray-300 flex-shrink-0" />
                      )}
                      <span className="text-sm font-sans font-medium text-[#141418]">
                        {signal.title}
                      </span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Output format */}
              <div>
                <label className="text-xs font-sans font-semibold text-gray-400 uppercase tracking-wider block mb-3">
                  Output Format
                </label>
                <div className="flex gap-2">
                  {OUTPUT_FORMATS.map((fmt) => (
                    <button
                      key={fmt}
                      type="button"
                      onClick={() => setOutputFormat(fmt)}
                      className={`px-4 py-2 rounded-xl text-sm font-sans font-medium transition-colors ${
                        outputFormat === fmt
                          ? 'bg-[#141418] text-white'
                          : 'bg-[#F6F3EF] text-[#141418] hover:bg-[#E8EDF1]'
                      }`}
                    >
                      {fmt}
                    </button>
                  ))}
                </div>
              </div>

              {/* Audience */}
              <div>
                <label className="text-xs font-sans font-semibold text-gray-400 uppercase tracking-wider block mb-3">
                  Audience
                </label>
                <div className="flex gap-2">
                  {AUDIENCES.map((aud) => (
                    <button
                      key={aud}
                      type="button"
                      onClick={() => setAudience(aud)}
                      className={`px-4 py-2 rounded-xl text-sm font-sans font-medium transition-colors ${
                        audience === aud
                          ? 'bg-[#141418] text-white'
                          : 'bg-[#F6F3EF] text-[#141418] hover:bg-[#E8EDF1]'
                      }`}
                    >
                      {aud}
                    </button>
                  ))}
                </div>
              </div>

              {/* Generate button */}
              <button
                type="button"
                onClick={handleGenerate}
                disabled={selectedCount === 0}
                className="w-full py-3 rounded-xl bg-[#6E879B] text-white font-sans font-medium text-sm hover:bg-[#5A7185] transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
              >
                Generate Brief (25 credits)
              </button>
            </>
          ) : (
            <>
              {/* Generated brief */}
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs font-sans font-medium text-gray-500">
                  Format: {outputFormat}
                </span>
                <span className="text-gray-300">|</span>
                <span className="text-xs font-sans font-medium text-gray-500">
                  Audience: {audience}
                </span>
              </div>

              <div className="bg-[#F6F3EF] rounded-xl p-5">
                <pre className="text-sm font-sans text-[#141418] leading-relaxed whitespace-pre-wrap">
                  {DEMO_BRIEF}
                </pre>
              </div>

              {/* Evidence & Logic */}
              <div className="border border-[#6E879B]/10 rounded-xl overflow-hidden">
                <button
                  type="button"
                  onClick={() => setShowEvidence(!showEvidence)}
                  className="w-full flex items-center justify-between px-4 py-3 hover:bg-[#F6F3EF] transition-colors"
                >
                  <span className="text-xs font-sans font-semibold text-[#6E879B] uppercase tracking-wider">
                    Evidence & Logic
                  </span>
                  {showEvidence ? (
                    <ChevronUp className="w-4 h-4 text-[#6E879B]" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-[#6E879B]" />
                  )}
                </button>
                {showEvidence && (
                  <div className="px-4 pb-4 space-y-2 border-t border-[#6E879B]/10 pt-3">
                    <p className="text-xs font-sans text-gray-400 mb-2">
                      Brief was generated using the following methodology and
                      sources:
                    </p>
                    {[
                      'SOCELLE market_signals table — selected signal data',
                      'Historical adoption curve analysis — 18-month lookback',
                      'RSS feed aggregation — 37+ professional beauty publications',
                      'SOCELLE platform analytics — training completion rates',
                    ].map((source, idx) => (
                      <div
                        key={idx}
                        className="flex items-start gap-2 text-xs font-sans text-gray-500"
                      >
                        <span className="text-[#6E879B] font-semibold flex-shrink-0">
                          [{idx + 1}]
                        </span>
                        <span>{source}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Back button */}
              <button
                type="button"
                onClick={() => setGenerated(false)}
                className="text-sm font-sans font-medium text-[#6E879B] hover:text-[#5A7185] transition-colors"
              >
                &larr; Generate another brief
              </button>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-[#6E879B]/10 bg-[#F6F3EF] flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs font-sans text-gray-400">
            <Bot className="w-3.5 h-3.5" />
            <span>Generated by AI — results may not be fully accurate</span>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-[#141418] text-white text-sm font-sans font-medium hover:bg-[#141418]/90 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
}
