import { useState } from 'react';
import {
  X,
  MessageSquare,
  ChevronDown,
  ChevronUp,
  Bot,
  CreditCard,
  TrendingUp,
  Shield,
  Target,
  Lightbulb,
} from 'lucide-react';

interface ExplainSignalProps {
  signalId: string;
  signalTitle?: string;
  onClose: () => void;
}

const DEMO_EXPLANATION = {
  summary:
    'This signal reflects a significant increase in consumer and professional interest in peptide-based skincare treatments across the medspa and clinical esthetics sector. Search volume for peptide facials has grown 34% quarter-over-quarter, driven by social media education content and new product launches from professional-grade brands.',
  confidenceScore: 0.87,
  contributingFactors: [
    {
      label: 'Search Volume Increase',
      detail:
        'Google Trends data shows a 34% QoQ increase in "peptide facial" and related queries across the US market.',
    },
    {
      label: 'Professional Adoption',
      detail:
        'Brand training module completions for peptide protocols increased 28% in the last 60 days on the SOCELLE platform.',
    },
    {
      label: 'Product Launch Density',
      detail:
        '4 major professional brands launched peptide-focused product lines in Q1 2026, up from 1 in Q1 2025.',
    },
    {
      label: 'Social Media Signals',
      detail:
        'Creator content featuring peptide treatments saw 2.1x higher engagement rates compared to the skincare category average.',
    },
  ],
  recommendedActions: [
    'Add a peptide facial to your treatment menu within the next 30 days to capture early demand.',
    'Request product samples from top-ranked peptide brands on SOCELLE.',
    'Complete the SOCELLE peptide protocol certification to boost your provider profile visibility.',
    'Monitor the Local Market View for your zip code to track peptide demand in your area.',
  ],
  sources: [
    'Google Trends API — peptide skincare queries (Feb-Mar 2026)',
    'SOCELLE platform data — brand training completions',
    'Open Beauty Facts — ingredient trend index',
    'SOCELLE RSS feed aggregation — 12 professional beauty publications',
  ],
};

export function ExplainSignal({ signalTitle, onClose }: ExplainSignalProps) {
  const [showEvidence, setShowEvidence] = useState(false);
  const demo = DEMO_EXPLANATION;
  const confidenceLabel =
    demo.confidenceScore >= 0.8
      ? 'HIGH'
      : demo.confidenceScore >= 0.5
        ? 'MODERATE'
        : 'LOW';
  const confidenceColor =
    demo.confidenceScore >= 0.8
      ? 'text-[#5F8A72]'
      : demo.confidenceScore >= 0.5
        ? 'text-[#A97A4C]'
        : 'text-[#8E6464]';

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/40 z-50"
        onClick={onClose}
        role="presentation"
      />

      {/* Modal */}
      <div className="fixed inset-x-4 top-[5%] bottom-[5%] md:inset-x-auto md:left-1/2 md:-translate-x-1/2 md:w-full md:max-w-2xl z-50 flex flex-col bg-white rounded-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#6E879B]/10">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-[#E8EDF1] flex items-center justify-center">
              <MessageSquare className="w-4 h-4 text-[#6E879B]" />
            </div>
            <div>
              <h2 className="font-sans text-base font-semibold text-[#141418]">
                Explain Signal
              </h2>
              {signalTitle && (
                <p className="text-xs font-sans text-gray-400 truncate max-w-xs">
                  {signalTitle}
                </p>
              )}
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-[10px] font-semibold bg-[#A97A4C]/10 text-[#A97A4C] px-2 py-0.5 rounded-full">
              DEMO
            </span>
            <button
              type="button"
              onClick={onClose}
              className="w-8 h-8 rounded-lg hover:bg-[#F6F3EF] flex items-center justify-center transition-colors"
            >
              <X className="w-4 h-4 text-gray-400" />
            </button>
          </div>
        </div>

        {/* Body — scrollable */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-6">
          {/* Generated by AI badge */}
          <div className="flex items-center gap-2 text-xs font-sans text-gray-400">
            <Bot className="w-3.5 h-3.5" />
            <span>Generated by AI</span>
            <span className="mx-1">|</span>
            <CreditCard className="w-3.5 h-3.5" />
            <span>5 credits</span>
          </div>

          {/* Summary */}
          <div className="bg-[#F6F3EF] rounded-xl p-5">
            <p className="text-sm font-sans text-[#141418] leading-relaxed">
              {demo.summary}
            </p>
          </div>

          {/* Confidence */}
          <div className="flex items-center gap-3 px-4 py-3 rounded-xl border border-[#6E879B]/10">
            <Shield className="w-4 h-4 text-[#6E879B]" />
            <div className="flex-1">
              <p className="text-xs font-sans font-medium text-gray-500">
                Confidence Score
              </p>
              <p className={`text-sm font-sans font-bold ${confidenceColor}`}>
                {confidenceLabel} — {(demo.confidenceScore * 100).toFixed(0)}%
              </p>
            </div>
            <div className="w-24 h-2 bg-gray-200 rounded-full overflow-hidden">
              <div
                className="h-full bg-[#5F8A72] rounded-full"
                style={{ width: `${demo.confidenceScore * 100}%` }}
              />
            </div>
          </div>

          {/* Contributing Factors */}
          <div>
            <h3 className="text-xs font-sans font-semibold text-gray-400 uppercase tracking-wider mb-3 flex items-center gap-2">
              <TrendingUp className="w-3.5 h-3.5" />
              Contributing Factors
            </h3>
            <div className="space-y-3">
              {demo.contributingFactors.map((factor) => (
                <div
                  key={factor.label}
                  className="rounded-xl border border-[#6E879B]/10 p-4"
                >
                  <p className="text-sm font-sans font-semibold text-[#141418] mb-1">
                    {factor.label}
                  </p>
                  <p className="text-xs font-sans text-gray-500 leading-relaxed">
                    {factor.detail}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Recommended Actions */}
          <div>
            <h3 className="text-xs font-sans font-semibold text-gray-400 uppercase tracking-wider mb-3 flex items-center gap-2">
              <Target className="w-3.5 h-3.5" />
              Recommended Actions
            </h3>
            <div className="space-y-2">
              {demo.recommendedActions.map((action, idx) => (
                <div
                  key={idx}
                  className="flex items-start gap-3 rounded-xl bg-[#5F8A72]/5 border border-[#5F8A72]/10 p-3"
                >
                  <Lightbulb className="w-4 h-4 text-[#5F8A72] flex-shrink-0 mt-0.5" />
                  <p className="text-sm font-sans text-[#141418]">{action}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Evidence & Logic — expandable */}
          <div className="border border-[#6E879B]/10 rounded-xl overflow-hidden">
            <button
              type="button"
              onClick={() => setShowEvidence(!showEvidence)}
              className="w-full flex items-center justify-between px-4 py-3 hover:bg-[#F6F3EF] transition-colors"
            >
              <span className="text-xs font-sans font-semibold text-[#6E879B] uppercase tracking-wider">
                Evidence & Logic
              </span>
              {showEvidence ? (
                <ChevronUp className="w-4 h-4 text-[#6E879B]" />
              ) : (
                <ChevronDown className="w-4 h-4 text-[#6E879B]" />
              )}
            </button>
            {showEvidence && (
              <div className="px-4 pb-4 space-y-2 border-t border-[#6E879B]/10 pt-3">
                <p className="text-xs font-sans text-gray-400 mb-2">
                  This explanation was generated by analyzing the following data
                  sources:
                </p>
                {demo.sources.map((source, idx) => (
                  <div
                    key={idx}
                    className="flex items-start gap-2 text-xs font-sans text-gray-500"
                  >
                    <span className="text-[#6E879B] font-semibold flex-shrink-0">
                      [{idx + 1}]
                    </span>
                    <span>{source}</span>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-[#6E879B]/10 bg-[#F6F3EF] flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs font-sans text-gray-400">
            <Bot className="w-3.5 h-3.5" />
            <span>Generated by AI — results may not be fully accurate</span>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-[#141418] text-white text-sm font-sans font-medium hover:bg-[#141418]/90 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
}
