import { useState } from 'react';
import {
  X,
  Search,
  ChevronDown,
  ChevronUp,
  Bot,
  CreditCard,
  TrendingUp,
  TrendingDown,
  Minus,
  Shield,
} from 'lucide-react';

interface SignalSearchProps {
  onClose: () => void;
}

interface DemoResult {
  id: string;
  title: string;
  direction: 'up' | 'down' | 'stable';
  category: string;
  confidence: number;
  magnitude: number;
  summary: string;
}

const DEMO_RESULTS: DemoResult[] = [
  {
    id: 'demo-1',
    title: 'Peptide Facial Demand Surge',
    direction: 'up',
    category: 'Skincare Treatments',
    confidence: 0.87,
    magnitude: 34,
    summary:
      'Consumer search volume for peptide facials increased 34% QoQ, driven by social media education and professional brand launches.',
  },
  {
    id: 'demo-2',
    title: 'LED Light Therapy Adoption',
    direction: 'up',
    category: 'Device Treatments',
    confidence: 0.79,
    magnitude: 22,
    summary:
      'LED light therapy device purchases by spas increased 22% in the past quarter, with red light therapy leading adoption.',
  },
  {
    id: 'demo-3',
    title: 'Chemical Peel Market Stabilization',
    direction: 'stable',
    category: 'Skincare Treatments',
    confidence: 0.72,
    magnitude: 3,
    summary:
      'Chemical peel demand has stabilized at 2024 levels. Professional-grade peel product sales show flat growth with regional variance.',
  },
];

const directionConfig = {
  up: { icon: TrendingUp, cls: 'text-[#5F8A72]', label: 'Trending Up' },
  down: { icon: TrendingDown, cls: 'text-[#8E6464]', label: 'Trending Down' },
  stable: { icon: Minus, cls: 'text-gray-400', label: 'Stable' },
};

export function SignalSearch({ onClose }: SignalSearchProps) {
  const [query, setQuery] = useState('');
  const [hasSearched, setHasSearched] = useState(false);
  const [showEvidence, setShowEvidence] = useState(false);

  const handleSearch = () => {
    if (query.trim()) {
      setHasSearched(true);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleSearch();
    }
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/40 z-50"
        onClick={onClose}
        role="presentation"
      />

      {/* Panel — slide from right */}
      <div className="fixed inset-y-0 right-0 w-full max-w-lg z-50 flex flex-col bg-white shadow-2xl">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#6E879B]/10">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-[#E8EDF1] flex items-center justify-center">
              <Search className="w-4 h-4 text-[#6E879B]" />
            </div>
            <div>
              <h2 className="font-sans text-base font-semibold text-[#141418]">
                Signal Search
              </h2>
              <p className="text-xs font-sans text-gray-400">
                Intelligence-driven signal discovery
              </p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-[10px] font-semibold bg-[#A97A4C]/10 text-[#A97A4C] px-2 py-0.5 rounded-full">
              DEMO
            </span>
            <button
              type="button"
              onClick={onClose}
              className="w-8 h-8 rounded-lg hover:bg-[#F6F3EF] flex items-center justify-center transition-colors"
            >
              <X className="w-4 h-4 text-gray-400" />
            </button>
          </div>
        </div>

        {/* Search input */}
        <div className="px-6 py-4 border-b border-[#6E879B]/10">
          <div className="flex items-center gap-2 text-xs font-sans text-gray-400 mb-3">
            <Bot className="w-3.5 h-3.5" />
            <span>Generated by AI</span>
            <span className="mx-1">|</span>
            <CreditCard className="w-3.5 h-3.5" />
            <span>2 credits per search</span>
          </div>
          <div className="flex gap-2">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <input
                type="text"
                placeholder="Search for signals, trends, ingredients..."
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                onKeyDown={handleKeyDown}
                className="w-full pl-9 pr-3 py-2.5 text-sm font-sans rounded-xl border border-[#6E879B]/20 bg-[#F6F3EF] focus:outline-none focus:ring-2 focus:ring-[#6E879B]/30"
              />
            </div>
            <button
              type="button"
              onClick={handleSearch}
              disabled={!query.trim()}
              className="px-4 py-2.5 rounded-xl bg-[#141418] text-white text-sm font-sans font-medium hover:bg-[#141418]/90 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
            >
              Search
            </button>
          </div>
        </div>

        {/* Results — scrollable */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-4">
          {!hasSearched && (
            <div className="text-center py-16">
              <Search className="w-10 h-10 mx-auto mb-3 text-gray-300" />
              <p className="text-sm font-sans font-medium text-gray-500">
                Enter a query to search signals
              </p>
              <p className="text-xs font-sans text-gray-400 mt-1">
                Try &quot;peptide treatments&quot; or &quot;LED therapy demand&quot;
              </p>
            </div>
          )}

          {hasSearched && (
            <>
              <p className="text-xs font-sans text-gray-400">
                {DEMO_RESULTS.length} results for &quot;{query}&quot;
              </p>

              {DEMO_RESULTS.map((result) => {
                const dc = directionConfig[result.direction];
                const DirIcon = dc.icon;
                const confLabel =
                  result.confidence >= 0.8
                    ? 'HIGH'
                    : result.confidence >= 0.5
                      ? 'MODERATE'
                      : 'LOW';
                const confColor =
                  result.confidence >= 0.8
                    ? 'text-[#5F8A72]'
                    : result.confidence >= 0.5
                      ? 'text-[#A97A4C]'
                      : 'text-[#8E6464]';

                return (
                  <div
                    key={result.id}
                    className="rounded-xl border border-[#6E879B]/10 p-4 hover:bg-[#F6F3EF] transition-colors cursor-pointer"
                  >
                    <div className="flex items-start justify-between gap-3 mb-2">
                      <div className="flex items-center gap-2">
                        <DirIcon className={`w-4 h-4 flex-shrink-0 ${dc.cls}`} />
                        <p className="text-sm font-sans font-semibold text-[#141418]">
                          {result.title}
                        </p>
                      </div>
                      <span className={`text-sm font-sans font-bold ${dc.cls} flex-shrink-0`}>
                        {result.direction === 'up'
                          ? '+'
                          : result.direction === 'down'
                            ? '-'
                            : ''}
                        {result.magnitude}%
                      </span>
                    </div>

                    <p className="text-xs font-sans text-gray-500 mb-3 leading-relaxed">
                      {result.summary}
                    </p>

                    <div className="flex items-center gap-4">
                      <span className="text-[10px] font-sans font-medium text-gray-400 bg-[#F6F3EF] px-2 py-0.5 rounded-full">
                        {result.category}
                      </span>
                      <div className="flex items-center gap-1">
                        <Shield className="w-3 h-3 text-gray-400" />
                        <span className={`text-[10px] font-sans font-semibold ${confColor}`}>
                          {confLabel}
                        </span>
                      </div>
                    </div>
                  </div>
                );
              })}

              {/* Evidence & Logic */}
              <div className="border border-[#6E879B]/10 rounded-xl overflow-hidden mt-6">
                <button
                  type="button"
                  onClick={() => setShowEvidence(!showEvidence)}
                  className="w-full flex items-center justify-between px-4 py-3 hover:bg-[#F6F3EF] transition-colors"
                >
                  <span className="text-xs font-sans font-semibold text-[#6E879B] uppercase tracking-wider">
                    Evidence & Logic
                  </span>
                  {showEvidence ? (
                    <ChevronUp className="w-4 h-4 text-[#6E879B]" />
                  ) : (
                    <ChevronDown className="w-4 h-4 text-[#6E879B]" />
                  )}
                </button>
                {showEvidence && (
                  <div className="px-4 pb-4 space-y-2 border-t border-[#6E879B]/10 pt-3">
                    <p className="text-xs font-sans text-gray-400 mb-2">
                      Search results were matched against the following data
                      sources:
                    </p>
                    {[
                      'SOCELLE market_signals table — active signals',
                      'RSS feed aggregation — 37+ professional beauty publications',
                      'Google Trends API — keyword volume data',
                      'Open Beauty Facts — ingredient and product data',
                    ].map((source, idx) => (
                      <div
                        key={idx}
                        className="flex items-start gap-2 text-xs font-sans text-gray-500"
                      >
                        <span className="text-[#6E879B] font-semibold flex-shrink-0">
                          [{idx + 1}]
                        </span>
                        <span>{source}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-[#6E879B]/10 bg-[#F6F3EF] flex items-center justify-between">
          <div className="flex items-center gap-2 text-xs font-sans text-gray-400">
            <Bot className="w-3.5 h-3.5" />
            <span>Generated by AI — results may not be fully accurate</span>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-[#141418] text-white text-sm font-sans font-medium hover:bg-[#141418]/90 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </>
  );
}
