// ── Mock Notification Data ─────────────────────────────────────────
// WO-18: Realistic notification data for in-app notification center

import type { Notification } from './types';

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(now.getTime() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    type: 'intelligence_alert',
    channel: 'in_app',
    title: 'Trending: LED therapy protocols up 34% this quarter',
    body: 'LED light therapy adoption surged across medspas in Q1. Operators adding red-light protocols see 22% higher retention.',
    actionUrl: '/portal/intelligence',
    read: false,
    sentAt: hoursAgo(1),
    createdAt: hoursAgo(1),
  },
  {
    id: 'notif-002',
    type: 'reorder_reminder',
    channel: 'in_app',
    title: 'Low stock alert: Daily Microfoliant',
    body: 'You last ordered Dermalogica Daily Microfoliant 45 days ago. Based on your usage patterns, it may be time to restock.',
    actionUrl: '/portal/orders',
    read: false,
    sentAt: hoursAgo(3),
    createdAt: hoursAgo(3),
  },
  {
    id: 'notif-003',
    type: 'campaign_launch',
    channel: 'in_app',
    title: 'New campaign: Dermalogica Spring Renewal',
    body: 'Dermalogica launched Spring Renewal — 15% off for Elite tier retailers. Offer valid through April 15.',
    actionUrl: '/brands/dermalogica',
    read: false,
    sentAt: hoursAgo(5),
    createdAt: hoursAgo(5),
  },
  {
    id: 'notif-004',
    type: 'education_new',
    channel: 'in_app',
    title: 'New CE course: Advanced Chemical Peel Protocols',
    body: 'Earn 2.0 CE credits with our new Advanced Chemical Peel Protocols module. Covers Jessner, TCA, and combination peels.',
    actionUrl: '/education',
    read: false,
    sentAt: hoursAgo(8),
    createdAt: hoursAgo(8),
  },
  {
    id: 'notif-005',
    type: 'system',
    channel: 'in_app',
    title: 'Your account has been upgraded to Elite tier',
    body: 'Congratulations! Based on your order volume, you now qualify for Elite tier pricing and exclusive brand access.',
    read: false,
    sentAt: hoursAgo(12),
    createdAt: hoursAgo(12),
  },
  {
    id: 'notif-006',
    type: 'intelligence_alert',
    channel: 'in_app',
    title: 'Peer benchmark: Your AOV is 18% above average',
    body: 'Your average order value of $847 outperforms similar-sized medspas in your region by 18%. Top operators average $920.',
    actionUrl: '/portal/intelligence',
    read: true,
    sentAt: daysAgo(1),
    createdAt: daysAgo(1),
  },
  {
    id: 'notif-007',
    type: 'reorder_reminder',
    channel: 'in_app',
    title: 'Reorder reminder: HydraFacial serums',
    body: 'Your HydraFacial Perk serum inventory is running low based on your treatment volume. Reorder to avoid disruption.',
    actionUrl: '/portal/orders',
    read: true,
    sentAt: daysAgo(1),
    createdAt: daysAgo(1),
  },
  {
    id: 'notif-008',
    type: 'campaign_launch',
    channel: 'in_app',
    title: 'SkinCeuticals Q2 promo: Free display with $2,500+ orders',
    body: 'SkinCeuticals is offering a complimentary retail display unit for orders above $2,500 this quarter.',
    actionUrl: '/brands/skinceuticals',
    read: true,
    sentAt: daysAgo(2),
    createdAt: daysAgo(2),
  },
  {
    id: 'notif-009',
    type: 'enrichment_update',
    channel: 'in_app',
    title: 'Market data refreshed for your region',
    body: 'We updated local market intelligence for the Greater Austin area. 12 new competitor insights available.',
    actionUrl: '/portal/intelligence',
    read: true,
    sentAt: daysAgo(2),
    createdAt: daysAgo(2),
  },
  {
    id: 'notif-010',
    type: 'education_new',
    channel: 'in_app',
    title: 'New guide: Retail Attach Rate Optimization',
    body: 'Learn how top operators achieve 40%+ retail attach rates. Includes scripts, display strategies, and staff training tips.',
    actionUrl: '/education',
    read: true,
    sentAt: daysAgo(3),
    createdAt: daysAgo(3),
  },
  {
    id: 'notif-011',
    type: 'intelligence_alert',
    channel: 'in_app',
    title: 'Category shift: Peptide serums overtaking retinol',
    body: 'Peptide-based serums now outsell retinol in the professional channel for the first time. Consider portfolio rebalancing.',
    actionUrl: '/portal/intelligence',
    read: true,
    sentAt: daysAgo(4),
    createdAt: daysAgo(4),
  },
  {
    id: 'notif-012',
    type: 'system',
    channel: 'in_app',
    title: 'Platform maintenance scheduled',
    body: 'Socelle will undergo scheduled maintenance this Saturday from 2-4am CST. No action required.',
    read: true,
    sentAt: daysAgo(5),
    createdAt: daysAgo(5),
  },
  {
    id: 'notif-013',
    type: 'campaign_launch',
    channel: 'in_app',
    title: 'Environ: New retailer onboarding incentive',
    body: 'Environ is offering a 20% introductory discount for first-time retailers. Application window closes March 31.',
    actionUrl: '/brands/environ',
    read: true,
    sentAt: daysAgo(6),
    createdAt: daysAgo(6),
  },
  {
    id: 'notif-014',
    type: 'intelligence_alert',
    channel: 'in_app',
    title: 'New signal: GLP-1 impact on body treatments',
    body: 'GLP-1 medications are shifting demand toward skin tightening and body contouring. Operators should evaluate treatment mix.',
    actionUrl: '/portal/intelligence',
    read: true,
    sentAt: daysAgo(7),
    createdAt: daysAgo(7),
  },
];
