// ── AIToolbar — INTEL-WO-05 ──────────────────────────────────────────────
// Fixed bottom toolbar exposing 6 AI tools.
// Each tool is protected by CreditGate — insufficient credits → upgrade CTA.
// Tool calls go to ai-orchestrator edge function.
// "Generated by AI" disclosure on every output (§13 AI Safety).
// Pearl Mineral V2 tokens only.

import { useState, useCallback, useEffect, useRef } from 'react';
import { Search, MessageSquare, FileText, ClipboardList, FlaskConical, MapPin, X, Bot, Loader2 } from 'lucide-react';
import { useAuth } from '../../lib/auth';
import { supabase } from '../../lib/supabase';
import { useCreditBalance } from '../../lib/credits/useCreditBalance';
import type { IntelligenceSignal } from '../../lib/intelligence/types';

// ── Tool Definitions ──────────────────────────────────────────────────────

type ToolId = 'search' | 'explain' | 'brief' | 'plan' | 'rnd' | 'region';

// Credit cost in USD (e.g. 0.01 = 1 cent per run)
interface ToolDef {
  id: ToolId;
  label: string;
  icon: React.ElementType;
  creditCostUsd: number;
  toolType: string;
  description: string;
  placeholder: string;
}

const TOOLS: ToolDef[] = [
  {
    id: 'search',
    label: 'Search',
    icon: Search,
    creditCostUsd: 0.01,
    toolType: 'signal_search',
    description: 'Search signals by keyword or topic',
    placeholder: 'Search market signals...',
  },
  {
    id: 'explain',
    label: 'Explain',
    icon: MessageSquare,
    creditCostUsd: 0.02,
    toolType: 'explain_signal',
    description: 'Get a plain-language explanation of a signal',
    placeholder: 'Paste a signal title or question...',
  },
  {
    id: 'brief',
    label: 'Brief',
    icon: FileText,
    creditCostUsd: 0.05,
    toolType: 'menu_analysis',
    description: 'Generate an intelligence brief from selected signals',
    placeholder: 'Describe your focus area...',
  },
  {
    id: 'plan',
    label: 'Plan',
    icon: ClipboardList,
    creditCostUsd: 0.05,
    toolType: 'action_plan',
    description: 'Create a 30-day action plan from market signals',
    placeholder: 'Describe your business context...',
  },
  {
    id: 'rnd',
    label: 'R&D Scout',
    icon: FlaskConical,
    creditCostUsd: 0.03,
    toolType: 'rnd_scout',
    description: 'Scout ingredient and formulation signals',
    placeholder: 'Enter ingredient or treatment category...',
  },
  {
    id: 'region',
    label: 'Region',
    icon: MapPin,
    creditCostUsd: 0.02,
    toolType: 'regional_analysis',
    description: 'Analyze signals for a specific region or market',
    placeholder: 'Enter your region or market...',
  },
];

// ── AI Output component ───────────────────────────────────────────────────

function AIOutput({ content, onClose }: { content: string; onClose: () => void }) {
  return (
    <div className="absolute bottom-full left-0 right-0 mb-2 mx-4 bg-[#141418] border border-[#6E879B]/20 rounded-xl shadow-2xl max-h-80 overflow-y-auto">
      <div className="sticky top-0 bg-[#141418] border-b border-[#6E879B]/10 px-4 py-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Bot className="w-4 h-4 text-[#6E879B]" />
          <span className="text-xs font-sans font-semibold text-white/60 uppercase tracking-wider">Generated by AI</span>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="w-6 h-6 rounded flex items-center justify-center hover:bg-white/10 transition-colors"
        >
          <X className="w-4 h-4 text-white/60" />
        </button>
      </div>
      <div className="px-4 py-4">
        <p className="text-sm font-sans text-white/80 leading-relaxed whitespace-pre-wrap">{content}</p>
      </div>
      <div className="px-4 py-3 border-t border-[#6E879B]/10">
        <p className="text-[10px] font-sans text-white/30">
          AI-generated content. Verify with professional sources before acting. Not medical or legal advice.
        </p>
      </div>
    </div>
  );
}

// ── Credit insufficient prompt ────────────────────────────────────────────

// (InsufficientCreditsPrompt is inline in ToolModal — removed standalone component)

// ── Tool Modal ────────────────────────────────────────────────────────────

interface ToolModalProps {
  tool: ToolDef;
  /** Available USD balance */
  creditBalanceUsd: number;
  onClose: () => void;
  activeSignal?: IntelligenceSignal | null;
}

function ToolModal({ tool, creditBalanceUsd, onClose, activeSignal }: ToolModalProps) {
  const { user } = useAuth();
  const [input, setInput] = useState(activeSignal?.title ?? '');
  const [output, setOutput] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showInsufficientCredits, setShowInsufficientCredits] = useState(false);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const hasCredits = creditBalanceUsd >= tool.creditCostUsd;

  const handleRun = useCallback(async () => {
    if (!input.trim()) return;
    if (!hasCredits) {
      setShowInsufficientCredits(true);
      return;
    }

    setIsGenerating(true);
    setError(null);
    setOutput(null);

    try {
      const { data, error: fnError } = await supabase.functions.invoke('ai-orchestrator', {
        body: {
          tool_type: tool.toolType,
          input: input.trim(),
          user_id: user?.id,
          context: activeSignal
            ? {
                signal_id: activeSignal.id,
                signal_title: activeSignal.title,
                signal_category: activeSignal.category,
                signal_magnitude: activeSignal.magnitude,
              }
            : undefined,
        },
      });

      if (fnError) {
        const msg = fnError.message ?? '';
        // 402 — insufficient credits
        if (msg.includes('402') || msg.includes('insufficient')) {
          setShowInsufficientCredits(true);
          return;
        }
        // 403 — subscription tier insufficient
        if (msg.includes('403') || msg.includes('tier_insufficient')) {
          setError('This AI tool requires a higher subscription tier. Please upgrade your plan.');
          return;
        }
        // 429 — rate limit exceeded
        if (msg.includes('429') || msg.includes('rate_limit')) {
          setError('Rate limit exceeded. Please wait a moment and try again.');
          return;
        }
        throw new Error(msg || 'AI service unavailable');
      }

      const text =
        typeof data?.output === 'string'
          ? data.output
          : typeof data?.result === 'string'
          ? data.result
          : typeof data?.answer === 'string'
          ? data.answer
          : JSON.stringify(data, null, 2);

      setOutput(text);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  }, [input, hasCredits, tool, user, activeSignal]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) {
        e.preventDefault();
        handleRun();
      }
      if (e.key === 'Escape') {
        onClose();
      }
    },
    [handleRun, onClose],
  );

  const ToolIcon = tool.icon;

  return (
    <div className="absolute bottom-full left-0 right-0 mb-2 mx-4 bg-[#141418] border border-[#6E879B]/20 rounded-xl shadow-2xl">
      {/* Header */}
      <div className="px-4 py-3 border-b border-[#6E879B]/10 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <ToolIcon className="w-4 h-4 text-[#6E879B]" />
          <span className="text-sm font-sans font-semibold text-white">{tool.label}</span>
          <span className="text-[10px] font-sans text-white/30">·</span>
          <span className="text-[10px] font-sans text-[#A97A4C]">${tool.creditCostUsd.toFixed(2)}/run</span>
        </div>
        <button type="button" onClick={onClose} className="w-6 h-6 rounded flex items-center justify-center hover:bg-white/10 transition-colors">
          <X className="w-4 h-4 text-white/60" />
        </button>
      </div>

      {/* Input */}
      <div className="p-4">
        <p className="text-xs font-sans text-white/40 mb-2">{tool.description}</p>
        <textarea
          ref={inputRef}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={tool.placeholder}
          rows={3}
          className="w-full bg-white/5 border border-[#6E879B]/20 rounded-lg px-3 py-2 text-sm font-sans text-white placeholder-white/25 focus:outline-none focus:ring-1 focus:ring-[#6E879B]/40 resize-none"
        />
        <div className="flex items-center justify-between mt-3">
          <span className="text-[10px] font-sans text-white/25">⌘ + Enter to run</span>
          <button
            type="button"
            onClick={handleRun}
            disabled={isGenerating || !input.trim() || !hasCredits}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#6E879B] text-white text-sm font-sans font-medium hover:bg-[#5A7185] disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Bot className="w-4 h-4" />
                Run
              </>
            )}
          </button>
        </div>

        {/* Error */}
        {error && (
          <div className="mt-3 p-3 bg-[#8E6464]/10 border border-[#8E6464]/20 rounded-lg">
            <p className="text-xs font-sans text-[#8E6464]">{error}</p>
            <button
              type="button"
              onClick={handleRun}
              className="mt-2 text-xs font-sans font-medium text-[#6E879B] hover:text-white transition-colors"
            >
              Retry
            </button>
          </div>
        )}
      </div>

      {/* Insufficient Credits overlay */}
      {showInsufficientCredits && (
        <div className="px-4 pb-4">
          <div className="p-3 bg-[#A97A4C]/10 border border-[#A97A4C]/20 rounded-lg">
            <p className="text-xs font-sans font-semibold text-[#A97A4C] mb-1">Insufficient balance</p>
            <p className="text-xs font-sans text-white/50 mb-3">
              This tool costs ${tool.creditCostUsd.toFixed(2)} — your balance is ${creditBalanceUsd.toFixed(2)}.
            </p>
            <a
              href="/plans"
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-[#6E879B] text-white text-xs font-sans font-medium hover:bg-[#5A7185] transition-colors"
            >
              Top up credits
            </a>
          </div>
        </div>
      )}

      {/* Output */}
      {output && (
        <div className="border-t border-[#6E879B]/10 px-4 py-4 max-h-64 overflow-y-auto">
          <div className="flex items-center gap-2 mb-3">
            <Bot className="w-3.5 h-3.5 text-[#6E879B]" />
            <span className="text-[10px] font-sans font-semibold text-white/40 uppercase tracking-wider">Generated by AI</span>
          </div>
          <p className="text-sm font-sans text-white/80 leading-relaxed whitespace-pre-wrap">{output}</p>
          <p className="text-[10px] font-sans text-white/25 mt-4">
            AI-generated content. Verify with professional sources. Not medical or legal advice.
          </p>
        </div>
      )}
    </div>
  );
}

// ── Main AIToolbar ────────────────────────────────────────────────────────

interface AIToolbarProps {
  activeSignal?: IntelligenceSignal | null;
}

export function AIToolbar({ activeSignal }: AIToolbarProps = {}) {
  const { user, isAdmin } = useAuth();
  const { balance, loading: creditsLoading } = useCreditBalance();
  const [activeTool, setActiveTool] = useState<ToolId | null>(null);

  // balance.credit_balance_usd is the available USD balance
  const creditBalanceUsd = isAdmin ? Infinity : (balance?.credit_balance_usd ?? 0);

  // ESC closes active tool
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setActiveTool(null);
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, []);

  const handleToolClick = useCallback(
    (toolId: ToolId) => {
      setActiveTool((prev) => (prev === toolId ? null : toolId));
    },
    [],
  );

  const activeDef = TOOLS.find((t) => t.id === activeTool) ?? null;

  return (
    <div className="fixed bottom-0 left-0 right-0 z-40 bg-[#141418] border-t border-[#6E879B]/20 shadow-lg">
      {/* Tool modal panel */}
      {activeDef && (
        <ToolModal
          tool={activeDef}
          creditBalanceUsd={creditBalanceUsd}
          onClose={() => setActiveTool(null)}
          activeSignal={activeSignal}
        />
      )}

      {/* Toolbar row */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between py-2">
          {/* Tool buttons */}
          <div className="flex items-center gap-1 overflow-x-auto scrollbar-hide">
            {TOOLS.map((tool) => {
              const Icon = tool.icon;
              const isActive = activeTool === tool.id;
              const hasCredits = isAdmin || creditBalanceUsd >= tool.creditCostUsd;

              return (
                <button
                  key={tool.id}
                  type="button"
                  onClick={() => handleToolClick(tool.id)}
                  title={`${tool.description} ($${tool.creditCostUsd.toFixed(2)}/run)`}
                  className={`relative flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-sans font-medium transition-colors flex-shrink-0 ${
                    isActive
                      ? 'bg-[#6E879B] text-white'
                      : hasCredits
                      ? 'bg-white/10 text-white/80 hover:bg-white/20 hover:text-white'
                      : 'bg-white/5 text-white/40 hover:bg-white/10 hover:text-white/60'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                  <span className="hidden sm:inline">{tool.label}</span>
                  {/* Cost badge */}
                  {!creditsLoading && !isAdmin && (
                    <span
                      className={`text-[9px] font-semibold px-1 py-0.5 rounded leading-none ${
                        hasCredits
                          ? 'bg-[#5F8A72]/20 text-[#5F8A72]'
                          : 'bg-[#A97A4C]/20 text-[#A97A4C]'
                      }`}
                    >
                      ${tool.creditCostUsd.toFixed(2)}
                    </span>
                  )}
                  {isAdmin && (
                    <span className="text-[9px] font-semibold bg-[#6E879B]/20 text-[#6E879B] px-1 py-0.5 rounded leading-none hidden sm:inline">
                      ADMIN
                    </span>
                  )}
                </button>
              );
            })}
          </div>

          {/* Balance indicator */}
          {user && !isAdmin && (
            <div className="flex items-center gap-2 ml-3 flex-shrink-0">
              {creditsLoading ? (
                <div className="h-4 w-16 bg-white/10 rounded animate-pulse" />
              ) : (
                <span className="text-xs font-sans text-white/40">
                  <span className={creditBalanceUsd < 0.10 ? 'text-[#A97A4C]' : 'text-white/60'}>
                    {creditBalanceUsd === Infinity ? '∞' : `$${creditBalanceUsd.toFixed(2)}`}
                  </span>
                </span>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
