import type { IntelligenceSignal, MarketPulse } from './types';

// ── Market Pulse — aggregate platform metrics ──────────────────────
export const mockMarketPulse: MarketPulse = {
  total_professionals: 2847,
  total_brands: 156,
  active_signals: 342,
  signals_this_week: 28,
  trending_category: 'Advanced Facial Protocols',
};

// ── Helper: generate an ISO date in the recent past ────────────────
function hoursAgo(h: number): string {
  const d = new Date();
  d.setHours(d.getHours() - h);
  return d.toISOString();
}

// ── Intelligence Signals — 34 signals across all categories ────────
export const mockSignals: IntelligenceSignal[] = [
  // ━━ PRODUCT VELOCITY ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'pv-001',
    signal_type: 'product_velocity',
    signal_key: 'peptide-serums-velocity',
    title: 'Peptide Complex Serums',
    description: 'Professional-grade peptide serums showing reorder rate 2.3x category average across medspa accounts. Strongest velocity in the anti-aging serum category this quarter.',
    magnitude: 230,
    direction: 'up',
    category: 'Anti-aging',
    source: 'Order intelligence',
    related_brands: ['SkinCeuticals', 'Jan Marini', 'iS Clinical'],
    related_products: ['Copper Peptide Serum', 'Multi-Peptide Eye Complex'],
    updated_at: hoursAgo(3),
  },
  {
    id: 'pv-002',
    signal_type: 'product_velocity',
    signal_key: 'barrier-repair-kits',
    title: 'Barrier Repair Kits',
    description: 'Post-procedure barrier repair kits seeing 67% increase in first-time orders. Spas bundling these as mandatory aftercare, driving predictable restock cycles.',
    magnitude: 67,
    direction: 'up',
    category: 'Post-procedure',
    source: 'Category velocity',
    related_brands: ['Alastin', 'EltaMD'],
    updated_at: hoursAgo(6),
  },
  {
    id: 'pv-003',
    signal_type: 'product_velocity',
    signal_key: 'retinol-renewal-systems',
    title: 'Retinol Renewal Systems',
    description: 'Stepped retinol programs (0.25% to 1.0%) replacing single-strength products. Subscription-model velocity emerging as professionals guide clients through phased protocols.',
    magnitude: 41,
    direction: 'up',
    category: 'Anti-aging',
    source: 'Protocol intelligence',
    updated_at: hoursAgo(11),
  },
  {
    id: 'pv-004',
    signal_type: 'product_velocity',
    signal_key: 'vitamin-c-pro-backbar',
    title: 'Vitamin C Professional Backbar',
    description: 'L-ascorbic acid backbar concentrates holding steady. Not growing, but baseline demand remains strong as a foundational treatment-room ingredient across all business types.',
    magnitude: 2,
    direction: 'stable',
    category: 'Brightening',
    source: 'Order intelligence',
    updated_at: hoursAgo(18),
  },
  {
    id: 'pv-005',
    signal_type: 'product_velocity',
    signal_key: 'chemical-peel-solutions',
    title: 'Chemical Peel Solutions',
    description: 'Glycolic and TCA peel solutions showing slight decline as device-based resurfacing gains market share. Jessner peel orders down 12% quarter-over-quarter.',
    magnitude: 12,
    direction: 'down',
    category: 'Resurfacing',
    source: 'Category velocity',
    updated_at: hoursAgo(22),
  },

  // ━━ TREATMENT TRENDS ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'tt-001',
    signal_type: 'treatment_trend',
    signal_key: 'led-therapy-add-ons',
    title: 'LED Therapy Add-On Protocols',
    description: 'LED light therapy being added to 34% more facial protocols this quarter. Red (633nm) and near-infrared (830nm) wavelengths dominating as post-treatment recovery add-ons.',
    magnitude: 34,
    direction: 'up',
    category: 'Device protocols',
    source: 'Treatment intelligence',
    updated_at: hoursAgo(2),
  },
  {
    id: 'tt-002',
    signal_type: 'treatment_trend',
    signal_key: 'exosome-facial-protocols',
    title: 'Exosome Facial Protocols',
    description: 'Exosome-based treatments emerging as premium facial offering. Medspas reporting 3x higher average ticket when incorporating exosome serums into microneedling protocols.',
    magnitude: 42,
    direction: 'up',
    category: 'Premium treatments',
    source: 'Market intelligence',
    updated_at: hoursAgo(5),
  },
  {
    id: 'tt-003',
    signal_type: 'treatment_trend',
    signal_key: 'scalp-treatment-expansion',
    title: 'Scalp Treatment Menu Expansion',
    description: 'Scalp health treatments expanding beyond trichology clinics. Day spas and salons adding scalp analysis and LED scalp therapy to service menus, creating new product attachment opportunities.',
    magnitude: 28,
    direction: 'up',
    category: 'Service expansion',
    source: 'Menu intelligence',
    updated_at: hoursAgo(9),
  },
  {
    id: 'tt-004',
    signal_type: 'treatment_trend',
    signal_key: 'combination-resurfacing',
    title: 'Combination Resurfacing Protocols',
    description: 'Multi-modal resurfacing (chemical + mechanical + device) becoming standard. Professionals layering peels with dermaplaning and RF devices for enhanced outcomes.',
    magnitude: 22,
    direction: 'up',
    category: 'Advanced protocols',
    source: 'Protocol intelligence',
    updated_at: hoursAgo(14),
  },
  {
    id: 'tt-005',
    signal_type: 'treatment_trend',
    signal_key: 'express-facial-formats',
    title: 'Express Facial Formats',
    description: 'Sub-30-minute express facials growing as entry-level offering. These shorter formats are converting first-time facial clients at higher rates, with strong retail attachment.',
    magnitude: 19,
    direction: 'up',
    category: 'Service formats',
    source: 'Treatment intelligence',
    updated_at: hoursAgo(17),
  },

  // ━━ INGREDIENT MOMENTUM ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'im-001',
    signal_type: 'ingredient_momentum',
    signal_key: 'tranexamic-acid-rise',
    title: 'Tranexamic Acid',
    description: 'Tranexamic acid appearing in 18% more professional formulations this quarter. Gaining ground as targeted hyperpigmentation active, particularly in melasma-focused protocols.',
    magnitude: 18,
    direction: 'up',
    category: 'Hyperpigmentation',
    source: 'Formulation tracking',
    updated_at: hoursAgo(4),
  },
  {
    id: 'im-002',
    signal_type: 'ingredient_momentum',
    signal_key: 'polyglutamic-acid-hydration',
    title: 'Polyglutamic Acid',
    description: 'Polyglutamic acid (PGA) emerging as a leading hydration ingredient. Professional buyers noting 4x water-binding capacity versus hyaluronic acid in supplier education materials.',
    magnitude: 45,
    direction: 'up',
    category: 'Hydration',
    source: 'Ingredient intelligence',
    updated_at: hoursAgo(7),
  },
  {
    id: 'im-003',
    signal_type: 'ingredient_momentum',
    signal_key: 'exosome-technology-formulations',
    title: 'Exosome Technology',
    description: 'Exosome-derived growth factors appearing in 12% more professional serums. Moving from niche regenerative medicine into mainstream professional skincare channels.',
    magnitude: 12,
    direction: 'up',
    category: 'Biotech actives',
    source: 'Formulation tracking',
    updated_at: hoursAgo(8),
  },
  {
    id: 'im-004',
    signal_type: 'ingredient_momentum',
    signal_key: 'niacinamide-professional-demand',
    title: 'Niacinamide (Professional Grade)',
    description: 'High-concentration niacinamide (10%+) holding steady in professional demand. Barrier repair and sebum regulation applications maintaining baseline formulation presence.',
    magnitude: 3,
    direction: 'stable',
    category: 'Barrier support',
    source: 'Ingredient intelligence',
    updated_at: hoursAgo(15),
  },
  {
    id: 'im-005',
    signal_type: 'ingredient_momentum',
    signal_key: 'bakuchiol-plateauing',
    title: 'Bakuchiol',
    description: 'Bakuchiol interest plateauing after initial surge. Professionals noting it as a retinol alternative for sensitive clients but not replacing retinoids in advanced anti-aging protocols.',
    magnitude: 8,
    direction: 'down',
    category: 'Plant actives',
    source: 'Formulation tracking',
    updated_at: hoursAgo(20),
  },
  {
    id: 'im-006',
    signal_type: 'ingredient_momentum',
    signal_key: 'fermented-ingredients-surge',
    title: 'Fermented Actives',
    description: 'Fermented ingredient complexes (galactomyces, saccharomyces, lactobacillus) seeing renewed interest. K-beauty-influenced formulation approaches entering professional channels with stronger clinical data.',
    magnitude: 24,
    direction: 'up',
    category: 'Biotech actives',
    source: 'Ingredient intelligence',
    updated_at: hoursAgo(10),
  },

  // ━━ BRAND ADOPTION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'ba-001',
    signal_type: 'brand_adoption',
    signal_key: 'clinical-brand-expansion',
    title: 'Clinical Brands Expanding Accounts',
    description: '3 new clinical skincare brands each gained 50+ professional accounts this quarter. Evidence-based brands with strong clinical trial documentation showing fastest adoption curves.',
    magnitude: 50,
    direction: 'up',
    category: 'Brand growth',
    source: 'Account intelligence',
    updated_at: hoursAgo(6),
  },
  {
    id: 'ba-002',
    signal_type: 'brand_adoption',
    signal_key: 'korean-professional-brands',
    title: 'K-Beauty Professional Channel Entry',
    description: 'Korean professional brands entering the US wholesale market at accelerating pace. Medspas adopting K-beauty protocols, creating demand for professional-grade Korean formulations.',
    magnitude: 34,
    direction: 'up',
    category: 'Market entry',
    source: 'Brand intelligence',
    updated_at: hoursAgo(10),
  },
  {
    id: 'ba-003',
    signal_type: 'brand_adoption',
    signal_key: 'dtc-brands-going-pro',
    title: 'DTC Brands Launching Professional Lines',
    description: 'Consumer-first brands creating professional-only SKUs to enter the treatment room. 5 brands announced pro lines this quarter, seeking wholesale distribution partnerships.',
    magnitude: 28,
    direction: 'up',
    category: 'Channel expansion',
    source: 'Account intelligence',
    updated_at: hoursAgo(13),
  },
  {
    id: 'ba-004',
    signal_type: 'brand_adoption',
    signal_key: 'clean-clinical-adoption',
    title: 'Clean-Clinical Brands',
    description: 'Brands combining clean formulation with clinical efficacy data seeing strongest new-account growth. This hybrid positioning resonating particularly with boutique day spas.',
    magnitude: 38,
    direction: 'up',
    category: 'Brand positioning',
    source: 'Brand intelligence',
    updated_at: hoursAgo(16),
  },

  // ━━ REGIONAL ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'rg-001',
    signal_type: 'regional',
    signal_key: 'southwest-medspa-growth',
    title: 'Southwest Medspa Demand Surge',
    description: 'Arizona and Nevada medspas driving highest order volume growth regionally. Sun-damage and hyperpigmentation product categories dominating Southwest purchasing patterns.',
    magnitude: 31,
    direction: 'up',
    region: 'Southwest US',
    category: 'Regional demand',
    source: 'Geographic intelligence',
    updated_at: hoursAgo(5),
  },
  {
    id: 'rg-002',
    signal_type: 'regional',
    signal_key: 'northeast-clean-beauty-demand',
    title: 'Northeast Clean Beauty Priority',
    description: 'New York and New England spa operators showing strongest preference for clean and sustainable formulations. Ingredient transparency as top purchasing criterion in this region.',
    magnitude: 24,
    direction: 'up',
    region: 'Northeast US',
    category: 'Regional preference',
    source: 'Geographic intelligence',
    updated_at: hoursAgo(12),
  },
  {
    id: 'rg-003',
    signal_type: 'regional',
    signal_key: 'southeast-device-adoption',
    title: 'Southeast Device Protocol Adoption',
    description: 'Florida and Texas medspas leading in device-based treatment protocol adoption. RF and LED device accessory purchasing up 22% in the Southeast this quarter.',
    magnitude: 22,
    direction: 'up',
    region: 'Southeast US',
    category: 'Regional demand',
    source: 'Geographic intelligence',
    updated_at: hoursAgo(14),
  },

  // ━━ PRICING BENCHMARK ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'pb-001',
    signal_type: 'pricing_benchmark',
    signal_key: 'professional-serum-pricing',
    title: 'Professional Serum Wholesale Pricing',
    description: 'Average wholesale price for professional-grade serums (30ml) stabilizing at $42-$58 range. Premium peptide and growth factor serums commanding 40% higher margins versus standard active serums.',
    magnitude: 4,
    direction: 'stable',
    category: 'Pricing',
    source: 'Price intelligence',
    updated_at: hoursAgo(8),
  },
  {
    id: 'pb-002',
    signal_type: 'pricing_benchmark',
    signal_key: 'sunscreen-pricing-compression',
    title: 'Professional Sunscreen Price Compression',
    description: 'Professional sunscreen wholesale prices seeing slight compression as more brands enter the category. Tinted and mineral formulations maintaining price points better than chemical options.',
    magnitude: 7,
    direction: 'down',
    category: 'Pricing',
    source: 'Price intelligence',
    updated_at: hoursAgo(19),
  },

  // ━━ REGULATORY ALERT ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'ra-001',
    signal_type: 'regulatory_alert',
    signal_key: 'mocra-compliance-update',
    title: 'MoCRA Compliance Tracking',
    description: 'FDA MoCRA (Modernization of Cosmetics Regulation Act) compliance deadlines approaching. Brands with facility registration and adverse event reporting systems in place showing higher trust scores with professional buyers.',
    magnitude: 15,
    direction: 'up',
    category: 'Regulation',
    source: 'Regulatory tracking',
    updated_at: hoursAgo(3),
  },
  {
    id: 'ra-002',
    signal_type: 'regulatory_alert',
    signal_key: 'ingredient-transparency-requirements',
    title: 'Ingredient Disclosure Requirements',
    description: 'State-level ingredient disclosure requirements expanding. California and New York leading in requiring fuller ingredient transparency, influencing professional purchasing criteria nationally.',
    magnitude: 11,
    direction: 'up',
    category: 'Regulation',
    source: 'Regulatory tracking',
    updated_at: hoursAgo(16),
  },

  // ━━ EDUCATION ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    id: 'ed-001',
    signal_type: 'education',
    signal_key: 'protocol-completion-training',
    title: 'Protocol-Based Product Training',
    description: 'Brands offering protocol-based (not just product-based) education seeing 2.1x faster professional adoption. Treatment-room context for every product driving stronger ordering behavior.',
    magnitude: 210,
    direction: 'up',
    category: 'Professional education',
    source: 'Education intelligence',
    updated_at: hoursAgo(4),
  },
  {
    id: 'ed-002',
    signal_type: 'education',
    signal_key: 'device-certification-demand',
    title: 'Device Certification Programs',
    description: 'Demand for brand-certified device training programs up 29%. Professionals seeking certification as both skill validation and client trust differentiator.',
    magnitude: 29,
    direction: 'up',
    category: 'Professional education',
    source: 'Education intelligence',
    updated_at: hoursAgo(11),
  },
];
