import type { Campaign, AutomationRule, TierDiscount, VolumeDiscount } from './types';

export const MOCK_PRODUCTS = [
  { id: 'prod-001', name: 'Hydra-Renew Professional Serum' },
  { id: 'prod-002', name: 'Dermal Repair Complex 50ml' },
  { id: 'prod-003', name: 'Brightening Enzyme Peel' },
  { id: 'prod-004', name: 'Collagen Boost Ampoules (10pk)' },
  { id: 'prod-005', name: 'Barrier Recovery Moisturizer' },
  { id: 'prod-006', name: 'Vitamin C Clinical Concentrate' },
  { id: 'prod-007', name: 'Retinol Resurfacing Treatment' },
  { id: 'prod-008', name: 'Peptide Eye Complex' },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: 'camp-001',
    name: 'Spring Renewal Launch',
    description: 'Introduce the new Hydra-Renew line to elite and master operators with an exclusive early-access discount. Designed to drive protocol adoption across treatment rooms.',
    startDate: '2026-03-15',
    endDate: '2026-04-15',
    discountType: 'percentage',
    discountValue: 20,
    eligibleProducts: ['prod-001', 'prod-002', 'prod-005'],
    eligibleTiers: ['elite', 'master'],
    status: 'scheduled',
    targetOperatorCount: 84,
    createdAt: '2026-03-01',
  },
  {
    id: 'camp-002',
    name: 'Q1 Reorder Incentive',
    description: 'Encourage first-quarter reorders across the full catalog with a fixed-dollar credit for operators who place repeat orders within the promotional window.',
    startDate: '2026-01-10',
    endDate: '2026-03-31',
    discountType: 'fixed',
    discountValue: 75,
    eligibleProducts: ['prod-001', 'prod-002', 'prod-003', 'prod-004', 'prod-005', 'prod-006'],
    eligibleTiers: ['active', 'elite', 'master'],
    status: 'active',
    targetOperatorCount: 210,
    createdAt: '2026-01-05',
  },
  {
    id: 'camp-003',
    name: 'Brightening Protocol Push',
    description: 'Drive adoption of the Brightening Enzyme Peel and Vitamin C Concentrate as a paired protocol. Target medspas and clinics already offering corrective facials.',
    startDate: '2026-02-01',
    endDate: '2026-02-28',
    discountType: 'percentage',
    discountValue: 15,
    eligibleProducts: ['prod-003', 'prod-006'],
    eligibleTiers: ['elite', 'master'],
    status: 'completed',
    targetOperatorCount: 52,
    createdAt: '2026-01-20',
  },
  {
    id: 'camp-004',
    name: 'New Operator Welcome',
    description: 'Welcome newly approved operators with a first-order discount across the best-selling essentials. Drives initial activation and product trial.',
    startDate: '2026-04-01',
    endDate: '2026-06-30',
    discountType: 'percentage',
    discountValue: 25,
    eligibleProducts: ['prod-001', 'prod-005', 'prod-008'],
    eligibleTiers: ['active'],
    status: 'draft',
    targetOperatorCount: 40,
    createdAt: '2026-03-03',
  },
  {
    id: 'camp-005',
    name: 'Retinol Resurfacing Blitz',
    description: 'Limited-time promotion for the Retinol Resurfacing Treatment targeting advanced practitioners with anti-aging protocol focus.',
    startDate: '2026-05-01',
    endDate: '2026-05-31',
    discountType: 'fixed',
    discountValue: 50,
    eligibleProducts: ['prod-007'],
    eligibleTiers: ['master'],
    status: 'draft',
    targetOperatorCount: 28,
    createdAt: '2026-03-04',
  },
];

export const MOCK_AUTOMATIONS: AutomationRule[] = [
  {
    id: 'auto-001',
    name: 'Order Confirmation',
    type: 'order_confirmation',
    enabled: true,
    description: 'Send a branded confirmation email when an operator places a new order, including order summary and estimated fulfillment timeline.',
    lastTriggered: '2026-03-03',
    triggerCount: 347,
  },
  {
    id: 'auto-002',
    name: 'Shipping & Tracking Notification',
    type: 'shipping_notification',
    enabled: true,
    description: 'Automatically notify operators when their order ships with tracking information and expected delivery date.',
    lastTriggered: '2026-03-02',
    triggerCount: 298,
  },
  {
    id: 'auto-003',
    name: '60-Day Reorder Reminder',
    type: 'reorder_reminder',
    enabled: false,
    triggerDays: 60,
    description: 'Send a reorder reminder to operators who have not placed a follow-up order within 60 days of their last purchase.',
    lastTriggered: '2026-02-15',
    triggerCount: 89,
  },
];

export const MOCK_TIER_DISCOUNTS: TierDiscount[] = [
  {
    id: 'tier-001',
    tier: 'active',
    discountPercent: 5,
    description: 'Standard wholesale pricing for newly approved operators. Baseline discount on all SKUs.',
  },
  {
    id: 'tier-002',
    tier: 'elite',
    discountPercent: 12,
    minUnits: 50,
    description: 'Enhanced pricing for operators with consistent reorder history and 50+ units per quarter.',
  },
  {
    id: 'tier-003',
    tier: 'master',
    discountPercent: 18,
    minUnits: 150,
    description: 'Premium wholesale pricing for top-performing operators with 150+ units per quarter and protocol compliance.',
  },
];

export const MOCK_VOLUME_DISCOUNTS: VolumeDiscount[] = [
  {
    id: 'vol-001',
    minUnits: 25,
    maxUnits: 49,
    discountPercent: 3,
  },
  {
    id: 'vol-002',
    minUnits: 50,
    maxUnits: 99,
    discountPercent: 7,
  },
  {
    id: 'vol-003',
    minUnits: 100,
    maxUnits: undefined,
    discountPercent: 12,
  },
];
