import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import MainNav from '../../components/MainNav';
import SiteFooter from '../../components/sections/SiteFooter';
import { useCmsPage } from '../../lib/useCmsPage';

const SECTIONS = [
  {
    title: 'Acceptance of Terms',
    body: `By accessing or using Socelle, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform.`,
  },
  {
    title: 'Description of Service',
    body: `Socelle is a brand intelligence platform that helps service businesses (spas, salons, wellness studios) discover and evaluate professional product brands. We provide intelligence-powered procurement tools, brand matching, protocol recommendations, and implementation planning capabilities.`,
  },
  {
    title: 'Account Responsibilities',
    body: `You are responsible for maintaining the security of your account credentials and for all activity that occurs under your account. You agree to provide accurate information when creating your account and to update it as needed.`,
  },
  {
    title: 'Content You Provide',
    body: `By uploading service menu content to Socelle, you grant us a limited license to process and analyze that content for the purpose of providing our services to you. You retain all ownership of your content. We do not share your menu or business data with other users or third parties.`,
  },
  {
    title: 'Prohibited Uses',
    body: `You may not use Socelle to violate any applicable laws or regulations, infringe on intellectual property rights, transmit harmful or malicious content, or attempt to reverse-engineer or interfere with our platform or infrastructure.`,
  },
  {
    title: 'Disclaimer of Warranties',
    body: `Socelle is provided "as is" without warranties of any kind. Brand match scores, protocol recommendations, and procurement guidance are generated by automated intelligence systems and should be considered guidance, not professional advice. We make no guarantees of specific revenue outcomes.`,
  },
  {
    title: 'Limitation of Liability',
    body: `To the maximum extent permitted by law, Socelle shall not be liable for indirect, incidental, or consequential damages arising out of your use of the platform.`,
  },
  {
    title: 'Changes to Terms',
    body: `We may update these terms from time to time. Continued use of Socelle after changes constitutes acceptance of the updated terms. We will notify users of material changes by email.`,
  },
  {
    title: 'Contact',
    body: `For questions about these terms, please contact us at legal@socelle.com.`,
  },
];

export default function Terms() {
  const { isLive: _cmsLive } = useCmsPage('terms');

  return (
    <div className="min-h-screen bg-mn-bg font-sans">
      <Helmet>
        <title>Terms of Service — Socelle</title>
        <meta name="description" content="Socelle terms of service. Read the terms governing your use of the professional beauty wholesale marketplace." />
        <meta property="og:title" content="Terms of Service — Socelle" />
        <meta property="og:description" content="Terms governing your use of the Socelle professional beauty intelligence platform." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://socelle.com/terms" />
        <meta property="og:image" content="https://socelle.com/og-image.svg" />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://socelle.com/terms" />
        <script type="application/ld+json">{JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'WebPage',
          name: 'Terms of Service — Socelle',
          description: 'Terms governing your use of the Socelle professional beauty intelligence platform.',
          url: 'https://socelle.com/terms',
          isPartOf: { '@type': 'WebSite', url: 'https://socelle.com', name: 'Socelle' },
        })}</script>
      </Helmet>
      <MainNav />

      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16 lg:py-24">
        <div className="mb-12">
          <p className="text-accent text-[11px] font-sans font-medium tracking-[0.25em] uppercase mb-4">Legal</p>
          <h1 className="font-sans font-semibold text-4xl text-graphite mb-3">Terms of Service</h1>
          <div className="w-10 h-px bg-accent/50 mb-5" />
          <p className="text-graphite/50 font-sans font-light text-sm">Last updated: January 2025</p>
        </div>

        <div className="space-y-10">
          <p className="text-graphite/60 font-sans leading-relaxed">
            These Terms of Service govern your use of Socelle and constitute a legally binding agreement
            between you and Socelle. Please read them carefully before using the platform.
          </p>

          {SECTIONS.map((section) => (
            <div key={section.title}>
              <h2 className="font-sans font-semibold text-graphite text-base mb-3">{section.title}</h2>
              <p className="text-graphite/60 font-sans leading-relaxed font-light text-sm">{section.body}</p>
            </div>
          ))}
        </div>

        <div className="mt-16 pt-8 border-t border-graphite/10 flex gap-6">
          <Link to="/privacy" className="text-sm text-graphite hover:underline font-sans font-medium">
            Privacy Policy
          </Link>
          <Link to="/" className="text-sm text-graphite/60 hover:text-graphite font-sans transition-colors">
            Back to home
          </Link>
        </div>
      </div>

      <SiteFooter />
    </div>
  );
}
