import { describe, it, expect } from 'vitest';
import { validateInput, validateOutput, blockedResult, withGuardrails } from './guardrails';

describe('validateInput', () => {
  it('blocks empty input', () => {
    const result = validateInput('', 'menuOrchestrator');
    expect(result.valid).toBe(false);
    expect(result.blocked).toBe(false);
  });

  it('blocks whitespace-only input', () => {
    const result = validateInput('   ', 'menuOrchestrator');
    expect(result.valid).toBe(false);
  });

  it('blocks hard-blocked medical terms', () => {
    const result = validateInput('What dosage of botox should I use?', 'menuOrchestrator');
    expect(result.valid).toBe(false);
    expect(result.blocked).toBe(true);
    expect(result.blockReason).toContain('medical terminology');
  });

  it('blocks "prescription" term', () => {
    const result = validateInput('Write me a prescription', 'planOrchestrator');
    expect(result.blocked).toBe(true);
  });

  it('blocks surgical terms', () => {
    const result = validateInput('Plan for surgical excision', 'menuOrchestrator');
    expect(result.blocked).toBe(true);
  });

  it('passes clean beauty input', () => {
    const result = validateInput('Analyze vitamin C serum trends', 'menuOrchestrator');
    expect(result.valid).toBe(true);
    expect(result.blocked).toBe(false);
    expect(result.warnings).toHaveLength(0);
  });

  it('warns on retinoid mentions', () => {
    const result = validateInput('Compare retinoid serum market share', 'menuOrchestrator');
    expect(result.valid).toBe(true);
    expect(result.blocked).toBe(false);
    expect(result.warnings.length).toBeGreaterThan(0);
    expect(result.warnings[0]).toContain('retinoid');
  });

  it('warns on multiple warning terms', () => {
    const result = validateInput(
      'Retinoid and hydroquinone combination analysis',
      'menuOrchestrator',
    );
    expect(result.valid).toBe(true);
    expect(result.warnings.length).toBe(2);
  });

  it('trims sanitized text', () => {
    const result = validateInput('  hello world  ', 'menuOrchestrator');
    expect(result.sanitizedText).toBe('hello world');
  });
});

describe('validateOutput', () => {
  it('wraps output with AI metadata', () => {
    const result = validateOutput({ score: 42 }, 'menuOrchestrator');
    expect(result.passed).toBe(true);
    expect(result.blocked).toBe(false);
    expect(result.data?.score).toBe(42);
    expect(result.meta.generatedByAI).toBe(true);
    expect(result.meta.engine).toBe('menuOrchestrator');
    expect(result.meta.disclaimer).toContain('Generated by AI');
  });

  it('includes provided citations', () => {
    const result = validateOutput({ score: 1 }, 'test', ['source1', 'source2']);
    expect(result.meta.citations).toEqual(['source1', 'source2']);
  });

  it('uses default citations when none provided', () => {
    const result = validateOutput({ score: 1 }, 'test');
    expect(result.meta.citations.length).toBeGreaterThan(0);
  });
});

describe('blockedResult', () => {
  it('returns blocked guardrail result', () => {
    const result = blockedResult('menuOrchestrator', 'Test block');
    expect(result.passed).toBe(false);
    expect(result.blocked).toBe(true);
    expect(result.blockReason).toBe('Test block');
    expect(result.meta.inputSanitized).toBe(false);
  });
});

describe('withGuardrails', () => {
  it('blocks execution for invalid input', async () => {
    const fn = async () => ({ result: 'should not run' });
    const result = await withGuardrails('test', 'prescribe medication', fn);
    expect(result.blocked).toBe(true);
    expect(result.passed).toBe(false);
  });

  it('executes and wraps valid input', async () => {
    const fn = async () => ({ analysis: 'vitamin C trend is up' });
    const result = await withGuardrails('test', 'Analyze vitamin C trends', fn);
    expect(result.passed).toBe(true);
    expect(result.data?.analysis).toBe('vitamin C trend is up');
    expect(result.meta.generatedByAI).toBe(true);
  });
});
