/**
 * AI Safety Guardrails — SOCELLE V3 (CLAUDE.md §O)
 *
 * Every AI engine output MUST pass through these guardrails before
 * being returned to the caller. Guardrails enforce:
 *   1. Input validation — block medical diagnoses, dosing, prescriptions.
 *   2. Output validation — ensure "Generated by AI" metadata, require
 *      source citations.
 *   3. Hard block list — medical terms that trigger refusal with a helpful
 *      message.
 *
 * NOTE: This file does NOT modify existing engine logic. Engines call
 * `validateInput()` before processing and `validateOutput()` after.
 */

import { createScopedLogger } from '../logger';

const log = createScopedLogger('Guardrails');

// ── Types ────────────────────────────────────────────────────────────────────

export interface GuardrailResult<T = unknown> {
  passed: boolean;
  blocked: boolean;
  blockReason?: string;
  data?: T;
  meta: GuardrailMeta;
}

export interface GuardrailMeta {
  generatedByAI: true;
  guardrailVersion: string;
  checkedAt: string;
  engine: string;
  inputSanitized: boolean;
  outputValidated: boolean;
  citations: string[];
  disclaimer: string;
}

export interface EngineOutput {
  /** The structured result from any engine */
  [key: string]: unknown;
}

// ── Constants ────────────────────────────────────────────────────────────────

const GUARDRAIL_VERSION = '1.0.0';

/**
 * Hard-blocked medical terms. If ANY of these appear in user input,
 * the engine refuses to process and returns a helpful message.
 */
const HARD_BLOCKED_TERMS: readonly string[] = [
  // Dosing / prescriptions
  'prescribe', 'prescription', 'dosage', 'dosing', 'milligram', 'mg dose',
  'units of botox', 'cc of filler', 'inject units',
  // Diagnoses
  'diagnose', 'diagnosis', 'clinical diagnosis', 'medical diagnosis',
  'prognosis',
  // Controlled substances
  'opioid', 'narcotic', 'controlled substance', 'schedule ii',
  'schedule iii', 'schedule iv',
  // Medical procedures outside scope
  'surgical', 'surgery', 'excision', 'incision', 'suture',
  'anesthesia', 'sedation',
] as const;

/**
 * Warning terms — not blocked but flagged. The output will include
 * a provider-override notice.
 */
const WARNING_TERMS: readonly string[] = [
  'retinoid', 'tretinoin', 'hydroquinone', 'steroid',
  'antibiotic', 'antifungal', 'corticosteroid',
  'contraindication', 'adverse reaction', 'allergic reaction',
  'pregnancy', 'breastfeeding', 'immunocompromised',
] as const;

const AI_DISCLAIMER =
  'Generated by AI. This analysis is for business planning purposes only and does not constitute medical advice, diagnosis, or treatment recommendations. Always consult a licensed healthcare professional for clinical decisions.';

// ── Input Validation ─────────────────────────────────────────────────────────

export interface InputValidationResult {
  valid: boolean;
  blocked: boolean;
  blockReason?: string;
  warnings: string[];
  sanitizedText?: string;
}

/**
 * Validate and sanitize user input before passing to any AI engine.
 * Returns `blocked: true` if hard-blocked terms are detected.
 */
export function validateInput(
  text: string,
  engine: string,
): InputValidationResult {
  if (!text || text.trim().length === 0) {
    return {
      valid: false,
      blocked: false,
      blockReason: 'Input text is empty.',
      warnings: [],
    };
  }

  const lowerText = text.toLowerCase();
  const warnings: string[] = [];

  // Check hard blocks
  for (const term of HARD_BLOCKED_TERMS) {
    if (lowerText.includes(term)) {
      log.warn('Hard-blocked term detected', { engine, term });
      return {
        valid: false,
        blocked: true,
        blockReason:
          `This request contains medical terminology ("${term}") that is outside ` +
          'the scope of SOCELLE\'s service menu analysis. For medical dosing, ' +
          'diagnoses, or prescriptions, please consult a licensed healthcare ' +
          'professional.',
        warnings: [],
      };
    }
  }

  // Check warning terms
  for (const term of WARNING_TERMS) {
    if (lowerText.includes(term)) {
      warnings.push(
        `Input mentions "${term}". Output will include a provider-override notice.`,
      );
    }
  }

  if (warnings.length > 0) {
    log.info('Warning terms detected in input', { engine, count: warnings.length });
  }

  return {
    valid: true,
    blocked: false,
    warnings,
    sanitizedText: text.trim(),
  };
}

// ── Output Validation ────────────────────────────────────────────────────────

/**
 * Wrap any engine output with guardrail metadata.
 * Ensures every result returned to the UI carries:
 *   - `generatedByAI: true`
 *   - A disclaimer string
 *   - Source citations (engine must provide these)
 *   - Timestamp of the guardrail check
 */
export function validateOutput<T extends EngineOutput>(
  data: T,
  engine: string,
  citations: string[] = [],
): GuardrailResult<T> {
  const meta: GuardrailMeta = {
    generatedByAI: true,
    guardrailVersion: GUARDRAIL_VERSION,
    checkedAt: new Date().toISOString(),
    engine,
    inputSanitized: true,
    outputValidated: true,
    citations: citations.length > 0
      ? citations
      : ['SOCELLE canonical protocol library', 'Spa menu input data'],
    disclaimer: AI_DISCLAIMER,
  };

  log.info('Output validated', { engine, citationCount: citations.length });

  return {
    passed: true,
    blocked: false,
    data,
    meta,
  };
}

/**
 * Create a blocked result (for when input validation fails).
 */
export function blockedResult(
  engine: string,
  reason: string,
): GuardrailResult<never> {
  return {
    passed: false,
    blocked: true,
    blockReason: reason,
    meta: {
      generatedByAI: true,
      guardrailVersion: GUARDRAIL_VERSION,
      checkedAt: new Date().toISOString(),
      engine,
      inputSanitized: false,
      outputValidated: false,
      citations: [],
      disclaimer: AI_DISCLAIMER,
    },
  };
}

// ── Convenience: wrap an entire engine call ──────────────────────────────────

/**
 * Wraps an engine function with input validation and output wrapping.
 *
 * Usage:
 * ```ts
 * const result = await withGuardrails(
 *   'menuOrchestrator',
 *   menuText,
 *   async () => runMenuAnalysis(planId, brandId, menuText),
 *   ['canonical_protocols', 'market_signals'],
 * );
 * ```
 */
export async function withGuardrails<T extends EngineOutput>(
  engine: string,
  inputText: string,
  fn: () => Promise<T>,
  citations?: string[],
): Promise<GuardrailResult<T>> {
  // 1. Validate input
  const inputCheck = validateInput(inputText, engine);
  if (!inputCheck.valid) {
    return blockedResult(engine, inputCheck.blockReason ?? 'Invalid input.');
  }

  // 2. Execute engine
  const result = await fn();

  // 3. Validate and wrap output
  return validateOutput(result, engine, citations);
}
