/// Conversation model — matches Socelle Supabase `conversations` table.
///
/// See SOCELLE_MASTER_PROMPT_FINAL.md § 14 for messaging architecture:
/// - 5 conversation types: direct, order_linked, brand_broadcast,
///   platform_announcement, system
/// - Participants identified by Supabase auth.users(id)
/// - Soft-archived (never hard deleted)
class Conversation {
  const Conversation({
    required this.id,
    required this.type,
    this.subject,
    this.participantOneId,
    this.participantTwoId,
    this.orderId,
    this.brandId,
    this.lastMessageAt,
    this.lastMessagePreview,
    this.isArchived = false,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;

  /// Conversation type — determines rendering and permission rules.
  final ConversationType type;

  /// Optional subject line (shown in inbox list).
  final String? subject;

  /// For direct and order_linked conversations.
  final String? participantOneId;
  final String? participantTwoId;

  /// For order_linked conversations — ties messages to an order.
  final String? orderId;

  /// For brand_broadcast and brand-scoped conversations.
  final String? brandId;

  /// Timestamp of the most recent message in this conversation.
  final DateTime? lastMessageAt;

  /// Preview text of the most recent message (truncated).
  final String? lastMessagePreview;

  /// Whether the conversation has been archived by the user.
  final bool isArchived;

  final DateTime createdAt;
  final DateTime updatedAt;

  factory Conversation.fromMap(Map<String, dynamic> map) {
    return Conversation(
      id: map['id'] as String,
      type: ConversationType.fromString(map['type'] as String? ?? 'direct'),
      subject: map['subject'] as String?,
      participantOneId: map['participant_one_id'] as String?,
      participantTwoId: map['participant_two_id'] as String?,
      orderId: map['order_id'] as String?,
      brandId: map['brand_id'] as String?,
      lastMessageAt: map['last_message_at'] != null
          ? DateTime.parse(map['last_message_at'] as String)
          : null,
      lastMessagePreview: map['last_message_preview'] as String?,
      isArchived: map['is_archived'] as bool? ?? false,
      createdAt: DateTime.parse(map['created_at'] as String),
      updatedAt: DateTime.parse(map['updated_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'type': type.value,
      'subject': subject,
      'participant_one_id': participantOneId,
      'participant_two_id': participantTwoId,
      'order_id': orderId,
      'brand_id': brandId,
      'last_message_at': lastMessageAt?.toIso8601String(),
      'last_message_preview': lastMessagePreview,
      'is_archived': isArchived,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

/// Conversation types per SOCELLE_MASTER_PROMPT § 14.
enum ConversationType {
  /// 1:1 between verified brand user and reseller user.
  direct('direct'),

  /// Messages attached to a specific order.
  orderLinked('order_linked'),

  /// Brand → entire reseller network or segment (Phase 2).
  brandBroadcast('brand_broadcast'),

  /// Platform admin → all brands/resellers (Phase 3+).
  platformAnnouncement('platform_announcement'),

  /// Auto-generated by platform (order shipped, application approved, etc.).
  system('system');

  const ConversationType(this.value);
  final String value;

  factory ConversationType.fromString(String s) {
    return ConversationType.values.firstWhere(
      (e) => e.value == s,
      orElse: () => ConversationType.direct,
    );
  }
}
