/// Message model — matches Socelle Supabase `messages` table.
///
/// See SOCELLE_MASTER_PROMPT_FINAL.md § 14:
/// - Messages are never hard deleted (soft delete → "This message was deleted")
/// - Attachments: jpg, png, webp, pdf, csv, xlsx allowed; max 10MB
/// - sender_role tracks the user's role at time of sending for display purposes
class Message {
  const Message({
    required this.id,
    required this.conversationId,
    this.senderId,
    this.senderRole,
    required this.body,
    this.bodyHtml,
    this.attachments = const [],
    required this.messageType,
    this.editedAt,
    this.deletedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  final String id;
  final String conversationId;

  /// Null for system-generated messages.
  final String? senderId;

  /// Role of sender at time of message (e.g. 'brand_admin', 'reseller',
  /// 'platform_admin'). Used for display badging.
  final String? senderRole;

  /// Plain text message body.
  final String body;

  /// Optional HTML-formatted body (Phase 3+ rich text).
  final String? bodyHtml;

  /// List of attachment objects: [{url, filename, size, mime_type}].
  final List<Map<String, dynamic>> attachments;

  /// Message origin type.
  final MessageType messageType;

  /// Non-null if the message was edited after sending.
  final DateTime? editedAt;

  /// Non-null if soft-deleted. UI shows "This message was deleted".
  final DateTime? deletedAt;

  final DateTime createdAt;
  final DateTime updatedAt;

  bool get isDeleted => deletedAt != null;
  bool get isEdited => editedAt != null;
  bool get isSystemMessage => messageType != MessageType.user;
  bool get hasAttachments => attachments.isNotEmpty;

  factory Message.fromMap(Map<String, dynamic> map) {
    return Message(
      id: map['id'] as String,
      conversationId: map['conversation_id'] as String,
      senderId: map['sender_id'] as String?,
      senderRole: map['sender_role'] as String?,
      body: map['body'] as String? ?? '',
      bodyHtml: map['body_html'] as String?,
      attachments: (map['attachments'] as List<dynamic>?)
              ?.map((e) => Map<String, dynamic>.from(e as Map))
              .toList() ??
          [],
      messageType:
          MessageType.fromString(map['message_type'] as String? ?? 'user'),
      editedAt: map['edited_at'] != null
          ? DateTime.parse(map['edited_at'] as String)
          : null,
      deletedAt: map['deleted_at'] != null
          ? DateTime.parse(map['deleted_at'] as String)
          : null,
      createdAt: DateTime.parse(map['created_at'] as String),
      updatedAt: DateTime.parse(map['updated_at'] as String),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'conversation_id': conversationId,
      'sender_id': senderId,
      'sender_role': senderRole,
      'body': body,
      'body_html': bodyHtml,
      'attachments': attachments,
      'message_type': messageType.value,
      if (editedAt != null) 'edited_at': editedAt!.toIso8601String(),
      if (deletedAt != null) 'deleted_at': deletedAt!.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }
}

/// Message origin type.
enum MessageType {
  /// Written by a human user.
  user('user'),

  /// Auto-generated by the platform (order status, application approved, etc.).
  system('system'),

  /// Brand broadcast to reseller segment (Phase 2).
  broadcast('broadcast'),

  /// Platform-wide announcement (Phase 3+).
  announcement('announcement');

  const MessageType(this.value);
  final String value;

  factory MessageType.fromString(String s) {
    return MessageType.values.firstWhere(
      (e) => e.value == s,
      orElse: () => MessageType.user,
    );
  }
}
